env = Environment()

env['APP_TARGET'] = 'ocvCaptureApp'
env['APP_SOURCES'] = ['ocvCaptureApp.cpp']
env['DEBUG'] = 0

# Cinder-OpenCV block
env = SConscript('../../../scons/SConscript', exports = ['env'])

SConscript('../../../../../scons/SConscript', exports = ['env'])

