Import('env')

_INCLUDES = [Dir('../include').abspath]

if env['PLATFORM'] == 'darwin':
	_LIBS = ['libopencv_calib3d.a', 'libopencv_contrib.a',
				'libopencv_core.a', 'libopencv_features2d.a',
				'libopencv_flann.a', 'libopencv_gpu.a',
				'libopencv_imgproc.a',
				'libopencv_legacy.a', 'libopencv_ml.a',
				'libopencv_nonfree.a', 'libopencv_objdetect.a', 'libopencv_video.a']
	_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _LIBS]
elif env['PLATFORM'] == 'win32':
	_LIBS = ['opencv_calib3d249.lib', 'opencv_contrib249.lib',
				'opencv_core249.lib', 'opencv_features2d249.lib',
				'opencv_flann249.lib', 'opencv_gpu249.lib',
				'opencv_highgui249.lib', 'opencv_imgproc249.lib',
				'opencv_legacy249.lib', 'opencv_ml249.lib',
				'opencv_nonfree249.lib', 'opencv_objdetect249.lib',
				'opencv_photo249.lib', 'opencv_stitching249.lib',
				'opencv_ts249.lib', 'opencv_video249.lib',
				'opencv_videostab249.lib']
	_LIBS = [Dir('../lib/vc12').abspath + '/' + s for s in _LIBS]
else:
	_LIBS = []

_LIBS = [File(s) for s in _LIBS]

env.Append(CPPPATH = _INCLUDES)
env.Append(LIBS = _LIBS)

Return('env')
